BOOL_LIT: "TRUE" | "FALSE"
BOOL_1OP: "!" | "~" | "not"
BOOL_2OP: "or" | "+" | "|" | "||" | "and" | "*" | "&" | "&&" | "impl" | "=>" | "iff" | "<=>"
INT_1OP: "+" | "-"
INT_2OP: "+" | "-" | "*" | "/" | "%"
NULL_LIT: "NULL"

top: _expr
_expr: _bool_type | _int_type | _null_type | _str_type

_bool_type: BOOL_LIT | bool_1op | bool_2op | "(" _bool_type ")"
bool_1op: BOOL_1OP _bool_type
bool_2op: _bool_type BOOL_2OP _bool_type

_int_type: int_lit | int_1op | int_2op | "(" _int_type ")"
int_lit: int_parts
int_parts: /[+-]?/ /([0-9]+b)?/ /[0-9'A-Za-z$_]+/
int_1op: INT_1OP _int_type
int_2op: _int_type INT_2OP _int_type

_null_type: NULL_LIT | "(" _null_type ")"

_str_type: str_expr | "(" _str_type ")"
str_expr: str_parts
str_parts: "\"" (_str_lit | _str_esc | _str_var)* "\""
_str_lit: /[^\x00-\x1F\x7F-\x9F\\{}]+/
_str_esc: /\\(n|t|"|\{|\}|\\|u[0-9a-fA-F]+)/
_str_var: "{" gs_expr "}"