top: expr
?expr: lit | "(" expr ")"
?lit: null | bool | b_int | string

NULL: "NULL"
null: NULL

BOOL: "TRUE" | "FALSE"
bool: BOOL

SIGN: /[+-]/
BASE: /[0-9]+/
INT10: /[0-9](?:'?[0-9])*/
INT64: /[0-9A-Za-z$_](?:'?[0-9A-Za-z$_])*/
b_int: SIGN? (INT10 | BASE "b" INT64)

STD_CHAR: /[^"\\\n\r\t]/
ESC_CHAR: /[nt"\\]/
HEX_CODE: /[0-9A-Fa-f]+/
string: "\"" (STD_CHAR | "\\" ESC_CHAR | "\\u{" HEX_CODE "}")* "\""